import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

//Importing components
import Header from "../components/Header";
import Landing from "../components/Landing";
import Solutions from "../components/Solutions";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Landing />
      <Solutions />
    </div>
  );
};

export default Home;
